<a href="https://www.kaggle.com/code/chowdhurysalwa/mlb-2-2assignment?scriptVersionId=348094053" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [53]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/binib1997/superstore/Superstore.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv
/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv

In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [55]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [56]:
list =  [1,2,3,4,5,6]
series = pd.Series(list)
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

# 2. Create series from a dictionary

In [57]:
dic = {
    'Name': 'Jasim',
     'ID':102,
     'Age': 20
}
series_dic = pd.Series(dic) 
series_dic

Name    Jasim
ID        102
Age        20
dtype: object

# 3. Create a series from dataframe

In [58]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [59]:

sepal = iris['sepal_width']
sepal

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

# 4. Apply below operations on a series to understand about a series

In [60]:
# head
# tail
# sample
# size
# dtype
# astype
# index
# values

# 5. Change data-type of a series

In [61]:
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [62]:
series.astype(float)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

# 6. Apply below mathematical operations on a series

In [63]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [64]:
sepal.count()

np.int64(150)

In [65]:
sepal.sum()

np.float64(458.1)

In [66]:
sepal.max()

4.4

In [67]:
sepal.mean()

np.float64(3.0540000000000003)

In [68]:
sepal.median()

3.0

In [69]:
sepal.mode()

0    3.0
Name: sepal_width, dtype: float64

In [70]:
sepal.std()

0.4335943113621737

In [71]:
sepal.var()

0.18800402684563763

In [72]:
sepal.min()

2.0

In [73]:
sepal.product()

np.float64(1.1974766996547608e+72)

In [74]:
sepal.describe()

count    150.000000
mean       3.054000
std        0.433594
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max        4.400000
Name: sepal_width, dtype: float64

# 7. Do 3 slicing operations on a series

In [75]:
sepal[2:5]

2    3.2
3    3.1
4    3.6
Name: sepal_width, dtype: float64

# Dataframe

# 1. Create a dataframe from a list

In [76]:
list = [
    [100,92,73],
    [43,94,85],
    [55,36,57],
]
col = ['Math','Bnagla','English']
list = pd.DataFrame(list,columns=col)

# 2. Apply below dataframe understanding operations

In [77]:
# head
# tail
# sample
# info
# isnull
# duplicated

In [78]:
list.head()

   Math  Bnagla  English
0   100      92       73
1    43      94       85
2    55      36       57

In [79]:
titanic.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [80]:
tips.sample(7)

     total_bill   tip     sex smoker  day    time  size
241       22.67  2.00    Male    Yes  Sat  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
68        20.23  2.01    Male     No  Sat  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
23        39.42  7.58    Male     No  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
90        28.97  3.00    Male    Yes  Fri  Dinner     2

In [81]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [82]:
tips.isnull()
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [83]:
tips.duplicated().sum()

np.int64(1)

# 2. Apply below dataframe attribute operations

In [84]:
# shape
# dtypes
# columns
# values

In [85]:
titanic.shape

(891, 12)

In [86]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [87]:
list.values

array([[100,  92,  73],
       [ 43,  94,  85],
       [ 55,  36,  57]])

In [88]:
list.columns

Index(['Math', 'Bnagla', 'English'], dtype='object')

# 3. Apply below mathematical operations on a feature taken from dataframe

In [89]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [90]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [91]:
tips[['total_bill','tip']].agg(['count','sum','product','min','mean','max','median'])

            total_bill            tip
count     2.440000e+02   2.440000e+02
sum       4.827770e+03   7.315800e+02
product  1.905349e+306  1.724917e+106
min       3.070000e+00   1.000000e+00
mean      1.978594e+01   2.998279e+00
max       5.081000e+01   1.000000e+01
median    1.779500e+01   2.900000e+00

In [92]:
titanic['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [93]:
titanic['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [94]:
titanic['Age'].std()

14.526497332334044

In [95]:
titanic['Age'].var()

211.0191247463081

# Selection and filtering

In [96]:
# loc
# iloc
# isin()
# logical operation (&, |, ~)

In [97]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [98]:
titanic.iloc[20:30,3:7:2]

                                                 Name   Age
20                               Fynney, Mr. Joseph J  35.0
21                              Beesley, Mr. Lawrence  34.0
22                        McGowan, Miss. Anna "Annie"  15.0
23                       Sloper, Mr. William Thompson  28.0
24                      Palsson, Miss. Torborg Danira   8.0
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  38.0
26                            Emir, Mr. Farred Chehab   NaN
27                     Fortune, Mr. Charles Alexander  19.0
28                      O'Dwyer, Miss. Ellen "Nellie"   NaN
29                                Todoroff, Mr. Lalio   NaN

In [99]:
titanic.loc[10:25,['Age','Fare']]

     Age     Fare
10   4.0  16.7000
11  58.0  26.5500
12  20.0   8.0500
13  39.0  31.2750
14  14.0   7.8542
15  55.0  16.0000
16   2.0  29.1250
17   NaN  13.0000
18  31.0  18.0000
19   NaN   7.2250
20  35.0  26.0000
21  34.0  13.0000
22  15.0   8.0292
23  28.0  35.5000
24   8.0  21.0750
25  38.0  31.3875

In [100]:
titanic['Age'].isin([38.0])

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [101]:
titanic[(titanic['Age'].isin([38.0])) & (titanic['Fare']>8.0500)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN
224,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.0,1,0,19943,90.0000,C93,S
332,333,0,1,"Graham, Mr. George Edward",male,38.0,0,1,PC 17582,153.4625,C91,S
357,358,0,2,"Funk, Miss. Annie Clemmer",female,38.0,0,0,237671,13.0000,NaN,S
471,472,0,3,"Cacic, Mr. Luka",male,38.0,0,0,315089,8.6625,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,227.5250,C45,C

In [102]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [103]:
temp = tips[(tips['day'].isin(['Sun']))|(tips['time'].isin(['Dinner']))]
temp

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [104]:
con= ~tips.isnull()
con

     total_bill   tip   sex  smoker   day  time  size
0          True  True  True    True  True  True  True
1          True  True  True    True  True  True  True
2          True  True  True    True  True  True  True
3          True  True  True    True  True  True  True
4          True  True  True    True  True  True  True
..          ...   ...   ...     ...   ...   ...   ...
239        True  True  True    True  True  True  True
240        True  True  True    True  True  True  True
241        True  True  True    True  True  True  True
242        True  True  True    True  True  True  True
243        True  True  True    True  True  True  True

[244 rows x 7 columns]

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [105]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [106]:
tips.loc[11:20,['total_bill','tip']]

    total_bill   tip
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92
16       10.33  1.67
17       16.29  3.71
18       16.97  3.50
19       20.65  3.35
20       17.92  4.08

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [107]:
tips.loc[0:20,['total_bill','tip','day']]

    total_bill   tip  day
0        16.99  1.01  Sun
1        10.34  1.66  Sun
2        21.01  3.50  Sun
3        23.68  3.31  Sun
4        24.59  3.61  Sun
5        25.29  4.71  Sun
6         8.77  2.00  Sun
7        26.88  3.12  Sun
8        15.04  1.96  Sun
9        14.78  3.23  Sun
10       10.27  1.71  Sun
11       35.26  5.00  Sun
12       15.42  1.57  Sun
13       18.43  3.00  Sun
14       14.83  3.02  Sun
15       21.58  3.92  Sun
16       10.33  1.67  Sun
17       16.29  3.71  Sun
18       16.97  3.50  Sun
19       20.65  3.35  Sat
20       17.92  4.08  Sat

# 3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [108]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [109]:
customer = tips[(tips['day'].isin(['Sun']))&(tips['total_bill']>20)]
customer

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
11        35.26  5.00  Female     No  Sun  Dinner     4
15        21.58  3.92    Male     No  Sun  Dinner     2
44        30.40  5.60    Male     No  Sun  Dinner     4
46        22.23  5.00    Male     No  Sun  Dinner     2
47        32.40  6.00    Male     No  Sun  Dinner     4
48        28.55  2.05    Male     No  Sun  Dinner     3
52        34.81  5.20  Female     No  Sun  Dinner     4
54        25.56  4.34    Male     No  Sun  Dinner     4
112       38.07  4.00    Male     No  Sun  Dinner     3
113       23.95  2.55    Male     No  Sun  Dinner     2
114       25.71  4.00  Female     No  Sun  Dinner     3
116       29.93  5.07    Male     No  Sun  Dinner     4
153       24.55  2.00    Male     No  Sun  Dinner     4
155       29.85  5.14  Female     No  Sun  Dinner     5
156       48.17  5.00    Male     No  Sun  Dinner     6
157       25.00  3.75  Female     No  Sun  Dinner     4
160       21.50  3.50    Male     No  Sun  Dinner     4
165       24.52  3.48    Male     No  Sun  Dinner     3
166       20.76  2.24    Male     No  Sun  Dinner     2
167       31.71  4.50    Male     No  Sun  Dinner     4
173       31.85  3.18    Male    Yes  Sun  Dinner     2
175       32.90  3.11    Male    Yes  Sun  Dinner     2
179       34.63  3.55    Male    Yes  Sun  Dinner     2
180       34.65  3.68    Male    Yes  Sun  Dinner     4
181       23.33  5.65    Male    Yes  Sun  Dinner     2
182       45.35  3.50    Male    Yes  Sun  Dinner     3
183       23.17  6.50    Male    Yes  Sun  Dinner     4
184       40.55  3.00    Male    Yes  Sun  Dinner     2
185       20.69  5.00    Male     No  Sun  Dinner     5
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
189       23.10  4.00    Male    Yes  Sun  Dinner     3

# 4. Select passengers who are male and age greater than 50 from titanic

In [110]:
tit = titanic[(titanic['Sex'].isin(['male']))&(titanic['Age']>50)]
tit

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.6500,E67,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.0000,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
406,407,0,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C
492,493,0,1,"Molson, Mr. Harry Markland",male,55.0,0,0,113787,30.5000,C30,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
582,583,0,2,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
631,632,0,3,"Lundahl, Mr. Johan Svensson",male,51.0,0,0,347743,7.0542,NaN,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
714,715,0,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [111]:
cus = tips[(tips['sex'].isin(['Female']))&(tips[['tip']]>5)]
cus

     total_bill  tip  sex smoker  day time  size
0           NaN  NaN  NaN    NaN  NaN  NaN   NaN
1           NaN  NaN  NaN    NaN  NaN  NaN   NaN
2           NaN  NaN  NaN    NaN  NaN  NaN   NaN
3           NaN  NaN  NaN    NaN  NaN  NaN   NaN
4           NaN  NaN  NaN    NaN  NaN  NaN   NaN
..          ...  ...  ...    ...  ...  ...   ...
239         NaN  NaN  NaN    NaN  NaN  NaN   NaN
240         NaN  NaN  NaN    NaN  NaN  NaN   NaN
241         NaN  NaN  NaN    NaN  NaN  NaN   NaN
242         NaN  NaN  NaN    NaN  NaN  NaN   NaN
243         NaN  NaN  NaN    NaN  NaN  NaN   NaN

[244 rows x 7 columns]

# groupby

# 1. group on region based in store dataframe

In [112]:
store

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [113]:
mst = store.groupby('Region')

# 2. Find region-wise average sales

In [114]:
mst['Sales'].mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

# 3. Find region-wise average profit

In [115]:
mst['Profit'].mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

# 4. Find region-wise maximum profit

In [116]:
mst['Profit'].max()

Region
Central    8399.9760
East       5039.9856
South      3177.4750
West       6719.9808
Name: Profit, dtype: float64

# 5. Apply multiple aggregate functions on region-wise sales

In [117]:
mst['Sales'].agg(['median','std','var'])

         median         std            var
Region
Central  45.980  632.779010  400409.275802
East     54.900  620.712652  385284.196615
South    54.594  774.796273  600309.263888
West     60.840  524.876877  275495.736259

# 6. group on region and category wise

In [118]:
cat = store.groupby(['Region','Category'])

# 7. Find region and category wise average sales

In [119]:
cat['Sales'].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [120]:
cat['Sales'].agg(['mean','min','max','sum'])

                               mean    min        max          sum
Region  Category
Central Furniture        340.534644  1.892   3504.900  163797.1638
        Office Supplies  117.458801  0.444   9892.740  167026.4150
        Technology       405.753124  1.980  17499.950  170416.3120
East    Furniture        346.574383  2.960   4416.174  208291.2040
        Office Supplies  120.044425  0.852   4663.736  205516.0550
        Technology       495.278469  2.970  11199.968  264973.9810
South   Furniture        353.309289  2.784   4297.644  117298.6840
        Office Supplies  126.282727  1.167   6354.950  125651.3130
        Technology       507.753952  1.584  22638.480  148771.9080
West    Furniture        357.302325  3.480   3610.848  252612.7435
        Office Supplies  116.422377  1.080   8187.650  220853.2490
        Technology       420.687533  0.990  13999.960  251991.8320

# Merging and joining

In [121]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [122]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [123]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [124]:
con = students.merge(results,how = 'inner')
con = con.merge(departments,on ='department')
con[['name','faculty','math','python']]

     name      faculty  math  python
0   Rahim  Engineering    85      90
1   Karim  Engineering    72      75
2   Hasan  Engineering    91      88
3   Nabil  Engineering    68      72
4  Tanvir  Engineering    77      80
5    Rafi     Business    88      92
6   Imran  Engineering    74      79
7    Arif  Engineering    95      96
8   Jahid     Business    81      85
9    Siam  Engineering    69      71

# 2. Department wise students count

In [125]:
students[['department','name','student_id']].groupby('department').count()

            name  student_id
department
BBA            5           5
CSE            9           9
EEE            6           6

# 3. Faculty wise department count

In [126]:
departments[['faculty','department']].groupby('faculty').count()

             department
faculty
Business              1
Engineering           3

# 4. Find department wise highest number on each subject

In [127]:
con = students.merge(results,how = 'inner')
con

   student_id    name department  math  python
0         101   Rahim        CSE    85      90
1         102   Karim        EEE    72      75
2         103   Hasan        CSE    91      88
3         105   Nabil        CSE    68      72
4         106  Tanvir        EEE    77      80
5         108    Rafi        BBA    88      92
6         109   Imran        CSE    74      79
7         111    Arif        CSE    95      96
8         112   Jahid        BBA    81      85
9         114    Siam        CSE    69      71

In [128]:
con[['math','python','department']].groupby('department').max()

            math  python
department
BBA           88      92
CSE           95      96
EEE           77      80

# 5. Find faculty wise highest number on each subject

In [129]:
find = con.merge(departments,how = 'inner')
find = find[['faculty','math','python']].groupby('faculty').max()
find

             math  python
faculty
Business       88      92
Engineering    95      96

# Time-series

In [130]:
# use climate dataset
climate

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 1. convert time into datetime

In [133]:
climate['date']=pd.to_datetime(climate['date'])

# 2. set date as index

In [134]:
climate = climate.set_index('date')

# 3. Select row of 13 january, 2015

In [135]:
climate.loc['2015-01-13']

meantemp          12.250
humidity          77.875
wind_speed         4.875
meanpressure    1017.125
Name: 2015-01-13 00:00:00, dtype: float64

# 4. Select rows contains in april 2017

In [143]:
climate.loc['2017-04-01':'2017-04-30']

Empty DataFrame
Columns: [meantemp, humidity, wind_speed, meanpressure]
Index: []

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [140]:
climate.loc['2014-09-11':'2014-09-25']

             meantemp   humidity  wind_speed  meanpressure
date
2014-09-11  26.571429  85.714286   17.825000   1005.571429
2014-09-12  28.500000  73.000000    1.625000   1005.125000
2014-09-13  29.375000  68.250000    4.162500   1004.000000
2014-09-14  29.125000  65.500000    6.712500   1004.250000
2014-09-15  29.625000  63.125000    6.712500   1004.250000
2014-09-16  30.625000  65.125000    6.250000   1002.250000
2014-09-17  30.625000  61.875000    7.400000   1002.125000
2014-09-18  30.500000  62.375000    6.712500   1003.875000
2014-09-19  31.000000  56.625000    4.175000   1003.500000
2014-09-20  31.125000  55.750000    4.400000   1002.875000
2014-09-21  30.500000  54.875000    5.562500   1003.625000
2014-09-22  30.625000  50.000000   13.437500   1004.500000
2014-09-23  31.000000  47.000000   30.685714   1004.285714
2014-09-24  29.625000  53.000000    8.100000   1006.250000
2014-09-25  30.000000  52.500000    9.725000   1007.750000

# 6. Calculate month-wise average windspeed

In [144]:
climate['wind_speed'].resample('ME').mean()

date
2013-01-31     4.833913
2013-02-28     7.474090
2013-03-31     8.757270
2013-04-30     8.046385
2013-05-31     8.943452
2013-06-30     9.593929
2013-07-31     7.358698
2013-08-31     7.384347
2013-09-30     7.593425
2013-10-31     2.836110
2013-11-30     4.252242
2013-12-31     4.986002
2014-01-31     5.560580
2014-02-28     6.402232
2014-03-31     7.123963
2014-04-30     8.868631
2014-05-31     8.576555
2014-06-30    10.111250
2014-07-31     7.528590
2014-08-31     7.665360
2014-09-30     8.054940
2014-10-31     3.988191
2014-11-30     3.126667
2014-12-31     4.133756
2015-01-31     5.261290
2015-02-28     6.317985
2015-03-31     7.701210
2015-04-30     8.530000
2015-05-31     9.065495
2015-06-30     8.769167
2015-07-31     8.580703
2015-08-31     5.477031
2015-09-30     7.229048
2015-10-31     4.930012
2015-11-30     2.117500
2015-12-31     3.795392
2016-01-31     4.285177
2016-02-29     5.950592
2016-03-31     7.204904
2016-04-30     9.687357
2016-05-31     9.506423
2016-06-30     9.052079
2016-07-31     6.207018
2016-08-31     7.168392
2016-09-30     7.508029
2016-10-31     7.291021
2016-11-30     5.993723
2016-12-31     6.132705
2017-01-31     0.000000
Freq: ME, Name: wind_speed, dtype: float64

# 7. Calculate month-wise highest meantemp

In [145]:
climate['meantemp'].resample('ME').max()

date
2013-01-31    16.500000
2013-02-28    20.800000
2013-03-31    29.166667
2013-04-30    32.125000
2013-05-31    38.714286
2013-06-30    37.166667
2013-07-31    33.857143
2013-08-31    32.500000
2013-09-30    32.750000
2013-10-31    30.833333
2013-11-30    23.428571
2013-12-31    18.000000
2014-01-31    16.625000
2014-02-28    19.625000
2014-03-31    26.250000
2014-04-30    33.250000
2014-05-31    35.250000
2014-06-30    38.500000
2014-07-31    36.625000
2014-08-31    34.125000
2014-09-30    31.250000
2014-10-31    31.000000
2014-11-30    24.125000
2014-12-31    25.000000
2015-01-31    15.125000
2015-02-28    23.125000
2015-03-31    28.500000
2015-04-30    32.875000
2015-05-31    37.750000
2015-06-30    37.625000
2015-07-31    35.714286
2015-08-31    32.625000
2015-09-30    33.000000
2015-10-31    30.000000
2015-11-30    24.000000
2015-12-31    19.250000
2016-01-31    20.142857
2016-02-29    23.875000
2016-03-31    30.000000
2016-04-30    35.687500
2016-05-31    38.272727
2016-06-30    38.200000
2016-07-31    34.187500
2016-08-31    33.809524
2016-09-30    33.444444
2016-10-31    33.269231
2016-11-30    25.640000
2016-12-31    21.208333
2017-01-31    10.000000
Freq: ME, Name: meantemp, dtype: float64

# 8. Year-wise maximum, minimum and average humidity

In [147]:
climate['humidity'].resample('YE').agg(['max','min','mean'])

                   max         min        mean
date
2013-12-31   94.000000   15.857143   63.046292
2014-12-31   96.857143   20.875000   59.767942
2015-12-31   98.000000   13.428571   61.430490
2016-12-31   94.300000   18.466667   58.740174
2017-12-31  100.000000  100.000000  100.000000

# 9. A new column contains previous 10 days average meantemp

In [152]:
climate['prev_day']=climate['meantemp'].rolling(10).mean()

In [153]:
climate

             meantemp    humidity  wind_speed  meanpressure   prev_day
date
2013-01-01  10.000000   84.500000    0.000000   1015.666667        NaN
2013-01-02   7.400000   92.000000    2.980000   1017.800000        NaN
2013-01-03   7.166667   87.000000    4.633333   1018.666667        NaN
2013-01-04   8.666667   71.333333    1.233333   1017.166667        NaN
2013-01-05   6.000000   86.833333    3.700000   1016.500000        NaN
...               ...         ...         ...           ...        ...
2016-12-28  17.217391   68.043478    3.547826   1015.565217  17.107129
2016-12-29  15.238095   87.857143    6.000000   1016.904762  16.845224
2016-12-30  14.095238   89.666667    6.266667   1017.904762  16.274748
2016-12-31  15.052632   87.000000    7.325000   1016.100000  15.975011
2017-01-01  10.000000  100.000000    0.000000   1016.000000  15.246440

[1462 rows x 5 columns]